name: Automation-flow

on: 
 push:
  branches:
   - main

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  stage2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  stage3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
  stage4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

